spring:
  application:
    name: NBE-12-14-2-Team06
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

springdoc:
  default-produces-media-type: application/json

# 모니터링 설정
management:
  endpoints:
    web:
      exposure:
        include: health      # health 만 공개. 나머지는 노출하지 않음
  endpoint:
    health:
      show-details: never    # DB 주소 같은 내부 정보는 숨김
